function [param_opt, param_std] = WCMcalibration(i,cali_option,par_opt,...
            param_0, select_par, ...
            fwd_in, ...
            obs, OF_param,debug)

% Compute optimal parameters and optionally their uncertainty
% for different options of calibration algorithms.
    
% Gabrielle De Lannoy - 13 March 2023        
%==========================================================================

fn          = fieldnames(param_0.m);
par_size    = length(select_par);       

if strcmp(cali_option,'pso')
       
   [param_opt, OF_iter_t_0, OF_iter_m_0, OF_iter_p_0 ] = ...
        pso_WCM_SSE(par_opt, ...
        fwd_in, ...
        obs, ...
        param_0, select_par, ...    
        OF_param);
   for p=1:par_size
    eval(['param_std.',fn{select_par(p)},' = NaN;']);
   end
   
elseif strcmp(cali_option,'DREAMZS')

   [Sequences,X,output,log_p,par_opt] = ...
        dreamzs_WCM_v2(i, par_opt,...
        param_0, select_par, ...
        fwd_in, ...
        obs, OF_param);

   [param_opt, param_mean, param_std, param_ens, ...
    param_Lb, param_Ub, ...
    OF_t_min, OF_Tb_m_min, OF_Tb_s_min, OF_p_min, ...
    OF_iter_t_0, par_cov_0 ] = ...
        DREAM2out_bare_v2(Sequences,par_opt,...
        select_par, param_0);

elseif strcmp(cali_option, 'sceua')
    
   [param_opt,bestf] = ...
        sceua_WCM(param_0,select_par,par_opt.maxn,...
        par_opt.kstop,par_opt.pcento,...
        par_opt.peps,par_opt.ngs,par_opt.seed,par_opt.iniflg,...
        fwd_in,obs,param_0.m.s_0,OF_param,debug);
   for p=1:par_size
    eval(['param_std.',fn{select_par(p)},' = NaN;']);
   end
   
elseif strcmp(cali_option, 'SCE_gent')

   [param_opt] = ... 
       SCE_gent(param_0, select_par, fwd_in, obs);
   
   for p=1:par_size
    eval(['param_std.',fn{select_par(p)},' = NaN;']);
   end
   
end

end
%-------------------------------EOF----------------------------------------
